// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Org is the predicate function for org builders.
type Org func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
