// Code generated by ent, DO NOT EDIT.

package ent

import (
	"userService/m/v2/ent/ingridient"
	"userService/m/v2/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	ingridientFields := schema.Ingridient{}.Fields()
	_ = ingridientFields
	// ingridientDescAlcohol is the schema descriptor for alcohol field.
	ingridientDescAlcohol := ingridientFields[2].Descriptor()
	// ingridient.DefaultAlcohol holds the default value on creation for the alcohol field.
	ingridient.DefaultAlcohol = ingridientDescAlcohol.Default.(float64)
	// ingridientDescID is the schema descriptor for id field.
	ingridientDescID := ingridientFields[0].Descriptor()
	// ingridient.DefaultID holds the default value on creation for the id field.
	ingridient.DefaultID = ingridientDescID.Default.(func() uuid.UUID)
}
