// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"userService/m/v2/ent/ingridient"
	"userService/m/v2/ent/predicate"
	"userService/m/v2/ent/stockpile"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// StockpileQuery is the builder for querying Stockpile entities.
type StockpileQuery struct {
	config
	ctx            *QueryContext
	order          []stockpile.OrderOption
	inters         []Interceptor
	predicates     []predicate.Stockpile
	withIngridient *IngridientQuery
	withFKs        bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StockpileQuery builder.
func (sq *StockpileQuery) Where(ps ...predicate.Stockpile) *StockpileQuery {
	sq.predicates = append(sq.predicates, ps...)
	return sq
}

// Limit the number of records to be returned by this query.
func (sq *StockpileQuery) Limit(limit int) *StockpileQuery {
	sq.ctx.Limit = &limit
	return sq
}

// Offset to start from.
func (sq *StockpileQuery) Offset(offset int) *StockpileQuery {
	sq.ctx.Offset = &offset
	return sq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (sq *StockpileQuery) Unique(unique bool) *StockpileQuery {
	sq.ctx.Unique = &unique
	return sq
}

// Order specifies how the records should be ordered.
func (sq *StockpileQuery) Order(o ...stockpile.OrderOption) *StockpileQuery {
	sq.order = append(sq.order, o...)
	return sq
}

// QueryIngridient chains the current query on the "ingridient" edge.
func (sq *StockpileQuery) QueryIngridient() *IngridientQuery {
	query := (&IngridientClient{config: sq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := sq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := sq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(stockpile.Table, stockpile.FieldID, selector),
			sqlgraph.To(ingridient.Table, ingridient.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, stockpile.IngridientTable, stockpile.IngridientColumn),
		)
		fromU = sqlgraph.SetNeighbors(sq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Stockpile entity from the query.
// Returns a *NotFoundError when no Stockpile was found.
func (sq *StockpileQuery) First(ctx context.Context) (*Stockpile, error) {
	nodes, err := sq.Limit(1).All(setContextOp(ctx, sq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{stockpile.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (sq *StockpileQuery) FirstX(ctx context.Context) *Stockpile {
	node, err := sq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Stockpile ID from the query.
// Returns a *NotFoundError when no Stockpile ID was found.
func (sq *StockpileQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(1).IDs(setContextOp(ctx, sq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{stockpile.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (sq *StockpileQuery) FirstIDX(ctx context.Context) int {
	id, err := sq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Stockpile entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Stockpile entity is found.
// Returns a *NotFoundError when no Stockpile entities are found.
func (sq *StockpileQuery) Only(ctx context.Context) (*Stockpile, error) {
	nodes, err := sq.Limit(2).All(setContextOp(ctx, sq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{stockpile.Label}
	default:
		return nil, &NotSingularError{stockpile.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (sq *StockpileQuery) OnlyX(ctx context.Context) *Stockpile {
	node, err := sq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Stockpile ID in the query.
// Returns a *NotSingularError when more than one Stockpile ID is found.
// Returns a *NotFoundError when no entities are found.
func (sq *StockpileQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = sq.Limit(2).IDs(setContextOp(ctx, sq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{stockpile.Label}
	default:
		err = &NotSingularError{stockpile.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (sq *StockpileQuery) OnlyIDX(ctx context.Context) int {
	id, err := sq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Stockpiles.
func (sq *StockpileQuery) All(ctx context.Context) ([]*Stockpile, error) {
	ctx = setContextOp(ctx, sq.ctx, "All")
	if err := sq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Stockpile, *StockpileQuery]()
	return withInterceptors[[]*Stockpile](ctx, sq, qr, sq.inters)
}

// AllX is like All, but panics if an error occurs.
func (sq *StockpileQuery) AllX(ctx context.Context) []*Stockpile {
	nodes, err := sq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Stockpile IDs.
func (sq *StockpileQuery) IDs(ctx context.Context) (ids []int, err error) {
	if sq.ctx.Unique == nil && sq.path != nil {
		sq.Unique(true)
	}
	ctx = setContextOp(ctx, sq.ctx, "IDs")
	if err = sq.Select(stockpile.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (sq *StockpileQuery) IDsX(ctx context.Context) []int {
	ids, err := sq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (sq *StockpileQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, sq.ctx, "Count")
	if err := sq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, sq, querierCount[*StockpileQuery](), sq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (sq *StockpileQuery) CountX(ctx context.Context) int {
	count, err := sq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (sq *StockpileQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, sq.ctx, "Exist")
	switch _, err := sq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (sq *StockpileQuery) ExistX(ctx context.Context) bool {
	exist, err := sq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StockpileQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (sq *StockpileQuery) Clone() *StockpileQuery {
	if sq == nil {
		return nil
	}
	return &StockpileQuery{
		config:         sq.config,
		ctx:            sq.ctx.Clone(),
		order:          append([]stockpile.OrderOption{}, sq.order...),
		inters:         append([]Interceptor{}, sq.inters...),
		predicates:     append([]predicate.Stockpile{}, sq.predicates...),
		withIngridient: sq.withIngridient.Clone(),
		// clone intermediate query.
		sql:  sq.sql.Clone(),
		path: sq.path,
	}
}

// WithIngridient tells the query-builder to eager-load the nodes that are connected to
// the "ingridient" edge. The optional arguments are used to configure the query builder of the edge.
func (sq *StockpileQuery) WithIngridient(opts ...func(*IngridientQuery)) *StockpileQuery {
	query := (&IngridientClient{config: sq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	sq.withIngridient = query
	return sq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		IngridientId uuid.UUID `json:"ingridientId,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Stockpile.Query().
//		GroupBy(stockpile.FieldIngridientId).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (sq *StockpileQuery) GroupBy(field string, fields ...string) *StockpileGroupBy {
	sq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StockpileGroupBy{build: sq}
	grbuild.flds = &sq.ctx.Fields
	grbuild.label = stockpile.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		IngridientId uuid.UUID `json:"ingridientId,omitempty"`
//	}
//
//	client.Stockpile.Query().
//		Select(stockpile.FieldIngridientId).
//		Scan(ctx, &v)
func (sq *StockpileQuery) Select(fields ...string) *StockpileSelect {
	sq.ctx.Fields = append(sq.ctx.Fields, fields...)
	sbuild := &StockpileSelect{StockpileQuery: sq}
	sbuild.label = stockpile.Label
	sbuild.flds, sbuild.scan = &sq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StockpileSelect configured with the given aggregations.
func (sq *StockpileQuery) Aggregate(fns ...AggregateFunc) *StockpileSelect {
	return sq.Select().Aggregate(fns...)
}

func (sq *StockpileQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range sq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, sq); err != nil {
				return err
			}
		}
	}
	for _, f := range sq.ctx.Fields {
		if !stockpile.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if sq.path != nil {
		prev, err := sq.path(ctx)
		if err != nil {
			return err
		}
		sq.sql = prev
	}
	return nil
}

func (sq *StockpileQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Stockpile, error) {
	var (
		nodes       = []*Stockpile{}
		withFKs     = sq.withFKs
		_spec       = sq.querySpec()
		loadedTypes = [1]bool{
			sq.withIngridient != nil,
		}
	)
	if sq.withIngridient != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, stockpile.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Stockpile).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Stockpile{config: sq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, sq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := sq.withIngridient; query != nil {
		if err := sq.loadIngridient(ctx, query, nodes, nil,
			func(n *Stockpile, e *Ingridient) { n.Edges.Ingridient = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (sq *StockpileQuery) loadIngridient(ctx context.Context, query *IngridientQuery, nodes []*Stockpile, init func(*Stockpile), assign func(*Stockpile, *Ingridient)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Stockpile)
	for i := range nodes {
		if nodes[i].ingridient_stock == nil {
			continue
		}
		fk := *nodes[i].ingridient_stock
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(ingridient.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "ingridient_stock" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (sq *StockpileQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := sq.querySpec()
	_spec.Node.Columns = sq.ctx.Fields
	if len(sq.ctx.Fields) > 0 {
		_spec.Unique = sq.ctx.Unique != nil && *sq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, sq.driver, _spec)
}

func (sq *StockpileQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(stockpile.Table, stockpile.Columns, sqlgraph.NewFieldSpec(stockpile.FieldID, field.TypeInt))
	_spec.From = sq.sql
	if unique := sq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if sq.path != nil {
		_spec.Unique = true
	}
	if fields := sq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, stockpile.FieldID)
		for i := range fields {
			if fields[i] != stockpile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := sq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := sq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := sq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := sq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (sq *StockpileQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(sq.driver.Dialect())
	t1 := builder.Table(stockpile.Table)
	columns := sq.ctx.Fields
	if len(columns) == 0 {
		columns = stockpile.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if sq.sql != nil {
		selector = sq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if sq.ctx.Unique != nil && *sq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range sq.predicates {
		p(selector)
	}
	for _, p := range sq.order {
		p(selector)
	}
	if offset := sq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := sq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StockpileGroupBy is the group-by builder for Stockpile entities.
type StockpileGroupBy struct {
	selector
	build *StockpileQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (sgb *StockpileGroupBy) Aggregate(fns ...AggregateFunc) *StockpileGroupBy {
	sgb.fns = append(sgb.fns, fns...)
	return sgb
}

// Scan applies the selector query and scans the result into the given value.
func (sgb *StockpileGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sgb.build.ctx, "GroupBy")
	if err := sgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockpileQuery, *StockpileGroupBy](ctx, sgb.build, sgb, sgb.build.inters, v)
}

func (sgb *StockpileGroupBy) sqlScan(ctx context.Context, root *StockpileQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(sgb.fns))
	for _, fn := range sgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*sgb.flds)+len(sgb.fns))
		for _, f := range *sgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*sgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StockpileSelect is the builder for selecting fields of Stockpile entities.
type StockpileSelect struct {
	*StockpileQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ss *StockpileSelect) Aggregate(fns ...AggregateFunc) *StockpileSelect {
	ss.fns = append(ss.fns, fns...)
	return ss
}

// Scan applies the selector query and scans the result into the given value.
func (ss *StockpileSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ss.ctx, "Select")
	if err := ss.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StockpileQuery, *StockpileSelect](ctx, ss.StockpileQuery, ss, ss.inters, v)
}

func (ss *StockpileSelect) sqlScan(ctx context.Context, root *StockpileQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ss.fns))
	for _, fn := range ss.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ss.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
