// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// IngridientsColumns holds the columns for the "ingridients" table.
	IngridientsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "alcohol", Type: field.TypeFloat64, Default: 0},
		{Name: "is_dry", Type: field.TypeBool, Default: false},
		{Name: "measurment_unit", Type: field.TypeEnum, Enums: []string{"ml", "g", "pcs"}, Default: "ml"},
	}
	// IngridientsTable holds the schema information for the "ingridients" table.
	IngridientsTable = &schema.Table{
		Name:       "ingridients",
		Columns:    IngridientsColumns,
		PrimaryKey: []*schema.Column{IngridientsColumns[0]},
	}
	// StockpilesColumns holds the columns for the "stockpiles" table.
	StockpilesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ingridient_id", Type: field.TypeUUID},
		{Name: "owner_id", Type: field.TypeUUID},
		{Name: "quantity", Type: field.TypeInt64},
		{Name: "ingridient_stock", Type: field.TypeUUID, Nullable: true},
	}
	// StockpilesTable holds the schema information for the "stockpiles" table.
	StockpilesTable = &schema.Table{
		Name:       "stockpiles",
		Columns:    StockpilesColumns,
		PrimaryKey: []*schema.Column{StockpilesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "stockpiles_ingridients_stock",
				Columns:    []*schema.Column{StockpilesColumns[4]},
				RefColumns: []*schema.Column{IngridientsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		IngridientsTable,
		StockpilesTable,
	}
)

func init() {
	StockpilesTable.ForeignKeys[0].RefTable = IngridientsTable
}
