// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Ingridient is the predicate function for ingridient builders.
type Ingridient func(*sql.Selector)

// Stockpile is the predicate function for stockpile builders.
type Stockpile func(*sql.Selector)
