basePath: /api/v1
info:
  contact: {}
paths:
  /ingridient:
    post:
      consumes:
      - application/json
      description: Add new ingridient to database
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: username
        in: body
        name: username
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Adds new ingridient
      tags:
      - example
  /inventory:
    get:
      consumes:
      - application/json
      description: Get complete list of all ingridients availible for user
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Gets list of all ingridients
      tags:
      - example
  /ping:
    get:
      consumes:
      - application/json
      description: do ping
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: ping
      tags:
      - example
swagger: "2.0"
