definitions:
  models.CheckUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.CreateOrgRequest:
    properties:
      name:
        type: string
      owner:
        type: string
    type: object
  models.CreateUserRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
  description: Manages users and organizations data
  title: User Service API
  version: "1.0"
paths:
  /health:
    get:
      responses:
        "200":
          description: OK
        default:
          description: ""
      summary: Get information if service is healthy
  /orgs:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          schema:
            type: body
      summary: Get all usernames
  /orgs/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateOrgRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: body
        "400":
          description: Bad request
          schema:
            type: body
      summary: Create a new organization
  /users:
    get:
      description: Debug-only endpoint, should not be called from api gateway
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          schema:
            type: body
      summary: Get all usernames
  /users/check:
    post:
      consumes:
      - application/json
      parameters:
      - description: Log in
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CheckUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Successful log in
          schema:
            type: body
        "400":
          description: Bad request
          schema:
            type: body
        "404":
          description: User not found
          schema:
            type: body
      summary: Check user data (Log in)
  /users/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: Create user
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.CreateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
          schema:
            type: body
      summary: Create a new user
swagger: "2.0"
