// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"users_service/ent/membership"
	"users_service/ent/org"
	"users_service/ent/predicate"
	"users_service/ent/user"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MembershipUpdate is the builder for updating Membership entities.
type MembershipUpdate struct {
	config
	hooks    []Hook
	mutation *MembershipMutation
}

// Where appends a list predicates to the MembershipUpdate builder.
func (mu *MembershipUpdate) Where(ps ...predicate.Membership) *MembershipUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetRole sets the "role" field.
func (mu *MembershipUpdate) SetRole(s string) *MembershipUpdate {
	mu.mutation.SetRole(s)
	return mu
}

// SetMemberID sets the "member" edge to the User entity by ID.
func (mu *MembershipUpdate) SetMemberID(id uuid.UUID) *MembershipUpdate {
	mu.mutation.SetMemberID(id)
	return mu
}

// SetNillableMemberID sets the "member" edge to the User entity by ID if the given value is not nil.
func (mu *MembershipUpdate) SetNillableMemberID(id *uuid.UUID) *MembershipUpdate {
	if id != nil {
		mu = mu.SetMemberID(*id)
	}
	return mu
}

// SetMember sets the "member" edge to the User entity.
func (mu *MembershipUpdate) SetMember(u *User) *MembershipUpdate {
	return mu.SetMemberID(u.ID)
}

// SetOrgID sets the "org" edge to the Org entity by ID.
func (mu *MembershipUpdate) SetOrgID(id uuid.UUID) *MembershipUpdate {
	mu.mutation.SetOrgID(id)
	return mu
}

// SetNillableOrgID sets the "org" edge to the Org entity by ID if the given value is not nil.
func (mu *MembershipUpdate) SetNillableOrgID(id *uuid.UUID) *MembershipUpdate {
	if id != nil {
		mu = mu.SetOrgID(*id)
	}
	return mu
}

// SetOrg sets the "org" edge to the Org entity.
func (mu *MembershipUpdate) SetOrg(o *Org) *MembershipUpdate {
	return mu.SetOrgID(o.ID)
}

// Mutation returns the MembershipMutation object of the builder.
func (mu *MembershipUpdate) Mutation() *MembershipMutation {
	return mu.mutation
}

// ClearMember clears the "member" edge to the User entity.
func (mu *MembershipUpdate) ClearMember() *MembershipUpdate {
	mu.mutation.ClearMember()
	return mu
}

// ClearOrg clears the "org" edge to the Org entity.
func (mu *MembershipUpdate) ClearOrg() *MembershipUpdate {
	mu.mutation.ClearOrg()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MembershipUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MembershipUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MembershipUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MembershipUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (mu *MembershipUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Role(); ok {
		_spec.SetField(membership.FieldRole, field.TypeString, value)
	}
	if mu.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.MemberTable,
			Columns: []string{membership.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.MemberTable,
			Columns: []string{membership.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.OrgTable,
			Columns: []string{membership.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.OrgTable,
			Columns: []string{membership.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MembershipUpdateOne is the builder for updating a single Membership entity.
type MembershipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MembershipMutation
}

// SetRole sets the "role" field.
func (muo *MembershipUpdateOne) SetRole(s string) *MembershipUpdateOne {
	muo.mutation.SetRole(s)
	return muo
}

// SetMemberID sets the "member" edge to the User entity by ID.
func (muo *MembershipUpdateOne) SetMemberID(id uuid.UUID) *MembershipUpdateOne {
	muo.mutation.SetMemberID(id)
	return muo
}

// SetNillableMemberID sets the "member" edge to the User entity by ID if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableMemberID(id *uuid.UUID) *MembershipUpdateOne {
	if id != nil {
		muo = muo.SetMemberID(*id)
	}
	return muo
}

// SetMember sets the "member" edge to the User entity.
func (muo *MembershipUpdateOne) SetMember(u *User) *MembershipUpdateOne {
	return muo.SetMemberID(u.ID)
}

// SetOrgID sets the "org" edge to the Org entity by ID.
func (muo *MembershipUpdateOne) SetOrgID(id uuid.UUID) *MembershipUpdateOne {
	muo.mutation.SetOrgID(id)
	return muo
}

// SetNillableOrgID sets the "org" edge to the Org entity by ID if the given value is not nil.
func (muo *MembershipUpdateOne) SetNillableOrgID(id *uuid.UUID) *MembershipUpdateOne {
	if id != nil {
		muo = muo.SetOrgID(*id)
	}
	return muo
}

// SetOrg sets the "org" edge to the Org entity.
func (muo *MembershipUpdateOne) SetOrg(o *Org) *MembershipUpdateOne {
	return muo.SetOrgID(o.ID)
}

// Mutation returns the MembershipMutation object of the builder.
func (muo *MembershipUpdateOne) Mutation() *MembershipMutation {
	return muo.mutation
}

// ClearMember clears the "member" edge to the User entity.
func (muo *MembershipUpdateOne) ClearMember() *MembershipUpdateOne {
	muo.mutation.ClearMember()
	return muo
}

// ClearOrg clears the "org" edge to the Org entity.
func (muo *MembershipUpdateOne) ClearOrg() *MembershipUpdateOne {
	muo.mutation.ClearOrg()
	return muo
}

// Where appends a list predicates to the MembershipUpdate builder.
func (muo *MembershipUpdateOne) Where(ps ...predicate.Membership) *MembershipUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MembershipUpdateOne) Select(field string, fields ...string) *MembershipUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Membership entity.
func (muo *MembershipUpdateOne) Save(ctx context.Context) (*Membership, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MembershipUpdateOne) SaveX(ctx context.Context) *Membership {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MembershipUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MembershipUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (muo *MembershipUpdateOne) sqlSave(ctx context.Context) (_node *Membership, err error) {
	_spec := sqlgraph.NewUpdateSpec(membership.Table, membership.Columns, sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Membership.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, membership.FieldID)
		for _, f := range fields {
			if !membership.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != membership.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Role(); ok {
		_spec.SetField(membership.FieldRole, field.TypeString, value)
	}
	if muo.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.MemberTable,
			Columns: []string{membership.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.MemberTable,
			Columns: []string{membership.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.OrgCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.OrgTable,
			Columns: []string{membership.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.OrgIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   membership.OrgTable,
			Columns: []string{membership.OrgColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(org.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Membership{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{membership.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
