// Code generated by ent, DO NOT EDIT.

package ent

import (
	"users_service/ent/membership"
	"users_service/ent/schema"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipFields[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
}
